[package]
name = "hello"
version = "0.1.0"
edition = "2021"
authors = ["Josef Šimánek <josef.simanek@gmail.com>"]
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.4" }
