version: 2.1
jobs:
  build:
    docker:
      - image: ruby:3.1.2
    environment:
      RB_SYS_FORCE_INSTALL_RUST_TOOLCHAIN: 'true'
    steps:
      - checkout
      - run:
          name: Instal Rust/Cargo dependencies
          command: apt-get update && apt-get install -y clang
      - run:
          name: Run the default task
          command: |
            gem update --system '3.3.26'
            gem install bundler -v '2.3.26'
            bundle install
            bundle exec rake
